src/store/actions/sign.ts, src/store/epics/wallets.ts, src/store/reducers/sign.ts
* update sign actions to add clearSignForms action
* update sign reducer to handle state change for clearSignForms
* update wallet epic to call clearSignForms on switch wallet
=> ABX-4334 Clear Sign/Verify Form On Wallet Change

src/store/reducers/connections.ts
This is needed so that there is always a connection. Can modify however we see fit, but I don't see a reason for not adding at least one default connection.
=> Need some default connections

package-lock.json, src/containers/AccountPanel.tsx, src/containers/__tests__/AccountPanel.test.tsx
* validate and store name change with surrounding whitespace removed
* update name length validation to require at least one non-whitespace character
=> ABX-4601 update Account Panel name validation

src/containers/ImportAccount.tsx, src/store/epics/wallet.ts
* update wallet epic as per add account to handle scenario of duplicate name
* update wallet epic to handle public key clash
=> ABX-4604 Update import account

package-lock.json, src/index-web.html, src/jira-issue-collector.js, src/web.tsx
* add jira issue collector script to index-web html file
=> ABX-4696 Add Jira Feedback to Wallet

.travis.yml, package-lock.json, src/store/epics/accounts.ts
* update account poll from 20 -> 10 seconds
* update travis.yml to remove electron-forge steps
* update package-lock.json
=> ABX-4717 Update Account Polling

package-lock.json, src/containers/TransferCurrency/ConfirmationPage.tsx, src/containers/TransferCurrency/TransferPage.tsx
https://bullioncapital.atlassian.net/browse/ABX-4690
Changed transfer button values as per ticket.
=> Change transfer button values

package-lock.json, src/containers/AccountPanel.tsx, src/containers/TransferCurrency/NewContactTransfer.tsx, src/containers/__tests__/TransferCurrency/__snapshots__/NewContactTransfer.test.tsx.snap, src/jira-issue-collector.js, src/store/reducers/transfer.ts
* Update Jira Issue Collector Data Submission
* Update 'Public Address' references to 'Kinesis Address'
=> Fixes -- kinesis address references and update jira collector

src/containers/Routing.tsx, src/containers/Transactions.tsx, src/services/kinesis.ts, src/store/actions/transactions.ts, src/store/epics/accounts.ts, src/store/reducers/transactions.ts, src/store/root-epic.ts, src/types/interfaces.ts
https://bullioncapital.atlassian.net/browse/ABX-4708
Removed grey space from the bottom of the page
Created new action and epic to load next page
Modified reducers to handle payload from both next page and polling
Created new function to fetch next page
=> Display next batch of transactions on scroll

src/components/ExchangePage.tsx, src/containers/Contacts/index.tsx, src/containers/Routing.tsx, src/containers/WalletCreation/Passphrase.tsx, src/style.scss
https://bullioncapital.atlassian.net/browse/ABX-4550 (Account panel)
https://bullioncapital.atlassian.net/browse/ABX-4683 (Recovery phrase)
Added AccountPanel to ContactPage
Changed wording and whitespace in the Passphrase component according to the ticket description
=> Bugfix/abx 4550 add account panel/abx 4683 change recovery phrase page

src/helpers/errors.ts, src/services/transfer.ts, src/store/actions/transactions.ts, src/store/epics/transfer.ts
https://bullioncapital.atlassian.net/browse/ABX-4735
Created HorizonError and added a different error message and toast colour based on that.
Added 10s timeout to the submitTransaction function.
Redirected to Dashboard on failed transaction.
=> ABX-4735-add-timeout-to-transaction

src/containers/Routing.tsx, src/store/reducers/transactions.ts
https://bullioncapital.atlassian.net/browse/ABX-4777
Reset currentPage and tranactionOpertations state properties on changing currency.
Removed margin from the bottom of wallet.
=> Transaction list does not change when switching between contracts

package-lock.json, src/components/SignTransactionForm.tsx, src/containers/SignTransactionForm.ts, src/services/kinesis.ts
* update fee to be shown in kinesis currency instead of stroops
* update amount and fee to also display currency (ie, KAG or KAU)
* add helper to services/kinesis to convert stroops to kinesis
=> ABX-4955 Update Sign Transaction Details

src/components/TermsAndConditions.tsx
change the link for terms of service
=> ABX-4888: change the link for terms of service

.travis.yml, package-lock.json, package.json, src/store/reducers/connections.ts, src/types/js-kinesis-sdk.d.ts
* update travis yml config for new kinesis.money bucket hosting
* update settings to provide live network details for mainnet, set default to mainnet
* update sdk version to latest, remove sdk types file as no longer needed
=> ABX-4969 wallet live release changes

src/components/TermsAndConditions.tsx
Rephrase the term and service sentence
=> ABX-4888 Rephrase the term and service sentence

package-lock.json, package.json
* update version of `js-kinesis-sdk` to `v0.9.9`
=> ABX-4996 update sdk version for http -> https of links

src/components/ExchangePage.tsx
* update url of link to mint kinesis to 'mint.abx.com'
=> ABX-5031 Update Exchange Page Mint Link

src/containers/Sidebar/index.tsx
https://bullioncapital.atlassian.net/browse/ABX-5072
=> Change & to ? in the href attribute

package-lock.json, src/containers/TransferCurrency/TransferPage.tsx, src/services/kinesis.ts, src/store/actions/transactions.ts, src/store/epics/transfer.ts, src/store/reducers/transfer.ts
Updates to the Transfer epic and TransferPage component to alleviate the problems around miscalculation of remaining balance, and allowing the user to transfer an amount that is clearly more than they have available to send.
=> ABX-4997 insufficient funds error

package-lock.json, src/components/Sign.tsx, src/helpers/alert.ts
Updates method of importing Sweet Alert so that it doesn't break.
Fix found as per this Github Issue: https://github.com/t4t5/sweetalert/issues/799#issuecomment-370228666
=> Updates sweet alert importing

src/components/TermsAndConditions.tsx
https://bullioncapital.atlassian.net/browse/ABX-7046
=> updates tos

package-lock.json, package.json, src/containers/TransferCurrency/TransferPage.tsx
Fix decimal place display value to 5 dp
=> Fix decimal places to 5
